kaggle:
  api_key_path: "~/.kaggle/kaggle.json"
  dataset: "shashanknecrothapa/ames-housing-dataset"
  download_path: "./iowa_dream/_rawfile"
  cleaned_path: "./iowa_dream/_cleanfile"

data_dict:
  ordinal_columns:
    count: 23
    columns:
      - lot_shape
      - utilities
      - land_slope
      - overall_qu
      - overall_cond
      - exter_qu
      - exter_cond
      - bsmt_qu
      - bsmt_cond
      - bsmt_exposure
      - bsmtfin_type_1
      - bsmtfin_type_2
      - heating_qu
      - electrical
      - kitchen_qu
      - functional
      - fireplace_qu
      - garage_finish
      - garage_qu
      - garage_cond
      - paved_drive
      - pool_qu
      - fence
  nominal_columns:
    count: 28
    columns:
      - ms_subclass
      - ms_zoning
      - street
      - alley
      - land_contour
      - lot_config
      - neighborhood
      - condition_1
      - condition_2
      - bldg_type
      - house_style
      - roof_style
      - roof_matl
      - exterior_1st
      - exterior_2nd
      - mas_vnr_type
      - foundation
      - heating
      - central_air
      - garage_type
      - sale_type
      - sale_condition
      - misc_feature
      - year_blt
      - year_remod/add
      - year_sold
      - garage_year_blt
      - mo_sold
  discrete_columns:
    count: 9
    columns:
      - bsmt_full_bath
      - bsmt_half_bath
      - full_bath
      - half_bath
      - bedroom_abvgr
      - kitchen_abvgr
      - totrms_abvgr
      - fireplaces
      - garage_cars
  continuous_columns:
    count: 19
    columns:
      - lot_frontage
      - lot_area
      - mas_vnr_area
      - bsmtfin_sf_1
      - bsmtfin_sf_2
      - bsmt_unf_sf
      - total_bsmt_sf
      - 1st_flr_sf
      - 2nd_flr_sf
      - low_qu_fin_sf
      - gr_liv_area
      - garage_area
      - wood_deck_sf
      - open_porch_sf
      - enclosed_porch
      - 3ssn_porch
      - screen_porch
      - pool_area
      - misc_val
  continuous_target:
    - saleprice
  identifiers:
    - pid

ordinal_mappings:
  - name: "garage_qu"
    values: ['Ex', 'Fa', 'Gd', 'NONE', 'Po', 'TA']
    mapping: {Ex: 5, Fa: 2, Gd: 4, NONE: 0, Po: 1, TA: 3}

  - name: "fireplace_qu"
    values: ['Ex', 'Fa', 'Gd', 'NONE', 'Po', 'TA']
    mapping: {Ex: 5, Fa: 2, Gd: 4, NONE: 0, Po: 1, TA: 3}

  - name: "kitchen_qu"
    values: ['Ex', 'Fa', 'Gd', 'Po', 'TA']
    mapping: {Ex: 4, Fa: 1, Gd: 3, Po: 0, TA: 2}

  - name: "heating_qu"
    values: ['Ex', 'Fa', 'Gd', 'Po', 'TA']
    mapping: {Ex: 4, Fa: 1, Gd: 3, Po: 0, TA: 2}

  - name: "bsmt_qu"
    values: ['Ex', 'Fa', 'Gd', 'NONE', 'Po', 'TA']
    mapping: {Ex: 5, Fa: 2, Gd: 4, NONE: 0, Po: 1, TA: 3}

  - name: "bsmt_cond"
    values: ['Ex', 'Fa', 'Gd', 'NONE', 'Po', 'TA']
    mapping: {Ex: 5, Fa: 2, Gd: 4, NONE: 0, Po: 1, TA: 3}

  - name: "exter_cond"
    values: ['Ex', 'Fa', 'Gd', 'Po', 'TA']
    mapping: {Ex: 4, Fa: 3, Gd: 1, Po: 0, TA: 2}

  - name: "lot_shape"
    values: ['IR1', 'IR2', 'IR3', 'Reg']
    mapping: {IR1: 1, IR2: 2, IR3: 3, Reg: 0}

  - name: "paved_drive"
    values: ['Y', 'P', 'N']
    mapping: {'Y': 2, 'P': 1, 'N': 0}



# Based on this plotting: https://www.tmwr.org/ames
university_proximity:
  # Close
  - category: 4
    neighborhoods:
      - OldTown
      - IDOTRR
      - BrkSide
      - SWISU
      - Crawfor
      - CollgCr
      - Landmrk
  # Moderate
  - category: 3
    neighborhoods:
      - Edwards
      - Sawyer
      - Mitchel
      - Timber
      - Somerst
      - Blmngtn
      - ClearCr
      - MeadowV
      - Veenker
  # Far
  - category: 2
    neighborhoods:
      - NAmes
      - NWAmes
      - StoneBr
      - NridgHt
      - NoRidge
      - BrDale
      - SawyerW
  # Very Far
  - category: 1
    neighborhoods:
      - Gilbert
      - NPkVill
      - Greens
      - Blueste
      - GrnHill

cleaned_data_dict:
  ordinal:
    count: 12
    columns:
      - lot_shape
      - overall_qu
      - overall_cond
      - exter_cond
      - heating_qu
      - kitchen_qu
      - fireplace_qu
      - garage_qu
      - paved_drive
      - neighborhood_score
      - bsmt_total_score
  nominal:
    count: 15
    columns:
      - ms_subclass
      - lot_config
      - condition_1
      - roof_style
      - mas_vnr_type
      - foundation
      - heating
      - electrical
      - sale_type
      - exterior_1st
      - year_blt
      - mo_sold
      - recession_period
      - university_proximity_category
  discrete:
    count: 6
    columns:
      - full_bath
      - half_bath
      - bedroom_abvgr
      - kitchen_quality_score
      - fire_place_score
      - garage_cars
  continuous:
    count: 8
    columns:
      - lot_frontage
      - lot_area
      - mas_vnr_area
      - bsmtfin_sf_1
      - total_bsmt_sf
      - 2nd_flr_sf
      - gr_liv_area
      - wood_deck_sf
      - timing_remodel_index

final_data_dict:
  ordinal:
    count: 8
    columns:
      - lot_shape
      - overall_score
      - exter_cond
      - heating_qu
      - garage_qu
      - paved_drive
      - bsmt_total_score
      - neighborhood_score
  nominal:
    count: 16
    columns:
      - ms_subclass
      - lot_config
      - condition_1
      - roof_style
      - mas_vnr_type
      - foundation
      - heating
      - electrical
      - sale_type
      - exterior_1st
      - year_blt
      - mo_sold
      - fire_place_score
      - kitchen_quality_score
      - recession_period
      - university_proximity_category
  discrete:
    count: 3
    columns:
      - total_bath
      - bedroom_abvgr
      - garage_cars
  continuous:
    count: 10
    columns:
      - lot_frontage
      - lot_area
      - mas_vnr_area
      - bsmtfin_sf_1
      - total_bsmt_sf
      - 2nd_flr_sf
      - gr_liv_area
      - wood_deck_sf
      - living_area_percentage
      - timing_remodel_index
