kaggle:
  api_key_path: "~/.kaggle/kaggle.json"
  dataset: "shashanknecrothapa/ames-housing-dataset"
  download_path: "./iowa_dream/_rawfile"
  cleaned_path: "./iowa_dream/_cleanfile"

data_dict:
  ordinal_columns:
    count: 23
    columns:
      - lot_shape
      - utilities
      - land_slope
      - overall_qu
      - overall_cond
      - exter_qu
      - exter_cond
      - bsmt_qu
      - bsmt_cond
      - bsmt_exposure
      - bsmtfin_type_1
      - bsmtfin_type_2
      - heating_qu
      - electrical
      - kitchen_qu
      - functional
      - fireplace_qu
      - garage_finish
      - garage_qu
      - garage_cond
      - paved_drive
      - pool_qu
      - fence
  nominal_columns:
    count: 28
    columns:
      - ms_subclass
      - ms_zoning
      - street
      - alley
      - land_contour
      - lot_config
      - neighborhood
      - condition_1
      - condition_2
      - bldg_type
      - house_style
      - roof_style
      - roof_matl
      - exterior_1st
      - exterior_2nd
      - mas_vnr_type
      - foundation
      - heating
      - central_air
      - garage_type
      - sale_type
      - sale_condition
      - misc_feature
      - year_blt
      - year_remod/add
      - year_sold
      - garage_year_blt
      - mo_sold
  discrete_columns:
    count: 9
    columns:
      - bsmt_full_bath
      - bsmt_half_bath
      - full_bath
      - half_bath
      - bedroom_abvgr
      - kitchen_abvgr
      - totrms_abvgr
      - fireplaces
      - garage_cars
  continuous_columns:
    count: 19
    columns:
      - lot_frontage
      - lot_area
      - mas_vnr_area
      - bsmtfin_sf_1
      - bsmtfin_sf_2
      - bsmt_unf_sf
      - total_bsmt_sf
      - 1st_flr_sf
      - 2nd_flr_sf
      - low_qu_fin_sf
      - gr_liv_area
      - garage_area
      - wood_deck_sf
      - open_porch_sf
      - enclosed_porch
      - 3ssn_porch
      - screen_porch
      - pool_area
      - misc_val
  continuous_target:
    - saleprice
  identifiers:
    - pid

ordinal_mappings:
  - name: "exter_qu"
    values: ['TA', 'Gd', 'Ex', 'Fa']
    mapping: {TA: 1, Gd: 2, Ex: 3, Fa: 0}

  - name: "bsmt_qu"
    values: ['TA', 'Gd', 'Ex', 'NONE', 'Fa', 'Po']
    mapping: {TA: 3, Gd: 4, Ex: 5, NONE: 0, Fa: 2, Po: 1}

  - name: "bsmt_exposure"
    values: ['Gd', 'No', 'Mn', 'Av', 'NONE']
    mapping: {Gd: 4, 'No': 1, Mn: 2, Av: 3, NONE: 0}

  - name: "heating_qu"
    values: ['Fa', 'TA', 'Ex', 'Gd', 'Po']
    mapping: {Fa: 1, TA: 2, Ex: 4, Gd: 3, Po: 0}

  - name: "kitchen_qu"
    values: ['TA', 'Gd', 'Ex', 'Fa', 'Po']
    mapping: {TA: 2, Gd: 3, Ex: 4, Fa: 1, Po: 0}

  - name: "fireplace_qu"
    values: ['Gd', 'NONE', 'TA', 'Po', 'Ex', 'Fa']
    mapping: {Gd: 4, NONE: 0, TA: 3, Po: 1, Ex: 5, Fa: 2}



# Based on this plotting: https://www.tmwr.org/ames
university_proximity:
  # Close
  - category: 4
    neighborhoods:
      - OldTown
      - IDOTRR
      - BrkSide
      - SWISU
      - Crawfor
      - CollgCr
      - Landmrk
  # Moderate
  - category: 3
    neighborhoods:
      - Edwards
      - Sawyer
      - Mitchel
      - Timber
      - Somerst
      - Blmngtn
      - ClearCr
      - MeadowV
      - Veenker
  # Far
  - category: 2
    neighborhoods:
      - NAmes
      - NWAmes
      - StoneBr
      - NridgHt
      - NoRidge
      - BrDale
      - SawyerW
  # Very Far
  - category: 1
    neighborhoods:
      - Gilbert
      - NPkVill
      - Greens
      - Blueste
      - GrnHill

cleaned_data_dict:
  ordinal:
    count: 8
    columns:
      - overall_qu
      - overall_cond
      - heating_qu
      - kitchen_qu
      - fireplace_qu
      - exter_qu
      - bsmt_qu
      - bsmt_exposure
  nominal:
    count: 8
    columns:
      - neighborhood
      - exterior_1st
      - mas_vnr_type
      - foundation
      - year_blt
      - mo_sold
      - year_sold
      - lot_config
  discrete:
    count: 4
    columns:
      - full_bath
      - half_bath
      - bedroom_abvgr
      - fireplaces
  continuous:
    count: 10
    columns:
      - lot_frontage
      - lot_area
      - bsmt_unf_sf
      - total_bsmt_sf
      - 2nd_flr_sf
      - gr_liv_area
      - garage_area
      - wood_deck_sf

glm_data_dict:
  categorical:
    ordinal:
      count: 4
      columns:
        - exter_qu
        - overall_score
        - interior_qu
        - university_proximity_category
        - has_2nd_floor
        - has_wood_deck
    nominal:
      count: 8
      columns:
        - exterior_1st
        - foundation
        - mas_vnr_type
        - season_indicator
        - lot_config
  numerical:
    count: 10
    columns:
      - total_bath
      - bedroom_abvgr
      - fireplaces
      - gr_liv_area
      - total_bsmt_sf
      - garage_area
      - lot_frontage
      - lot_area
      - age
      - pct_unf_sf
      - neighborhood_score
