kaggle:
  api_key_path: "~/.kaggle/kaggle.json"
  dataset: "shashanknecrothapa/ames-housing-dataset"
  download_path: "./iowa_dream/_rawfile"

data_dict:
  ordinal_columns:
    count: 23
    columns:
      - lot_shape
      - utilities
      - land_slope
      - overall_qu
      - overall_cond
      - exter_qu
      - exter_cond
      - bsmt_qu
      - bsmt_cond
      - bsmt_exposure
      - bsmtfin_type_1
      - bsmtfin_type_2
      - heating_qu
      - electrical
      - kitchen_qu
      - functional
      - fireplace_qu
      - garage_finish
      - garage_qu
      - garage_cond
      - paved_drive
      - pool_qu
      - fence
  nominal_columns:
    count: 23
    columns:
      - ms_subclass
      - ms_zoning
      - street
      - alley
      - land_contour
      - lot_config
      - neighborhood
      - condition_1
      - condition_2
      - bldg_type
      - house_style
      - roof_style
      - roof_matl
      - exterior_1st
      - exterior_2nd
      - mas_vnr_type
      - foundation
      - heating
      - central_air
      - garage_type
      - sale_type
      - sale_condition
      - misc_feature
  discrete_columns:
    count: 14
    columns:
      - year_blt
      - year_remod/add
      - bsmt_full_bath
      - bsmt_half_bath
      - full_bath
      - half_bath
      - bedroom_abvgr
      - kitchen_abvgr
      - totrms_abvgr
      - fireplaces
      - garage_year_blt
      - garage_cars
      - mo_sold
      - year_sold
  continuous_columns:
    count: 19
    columns:
      - lot_frontage
      - lot_area
      - mas_vnr_area
      - bsmtfin_sf_1
      - bsmtfin_sf_2
      - bsmt_unf_sf
      - total_bsmt_sf
      - 1st_flr_sf
      - 2nd_flr_sf
      - low_qu_fin_sf
      - gr_liv_area
      - garage_area
      - wood_deck_sf
      - open_porch_sf
      - enclosed_porch
      - 3ssn_porch
      - screen_porch
      - pool_area
      - misc_val
  continuous_target:
      - saleprice
  identifiers:
    - pid

ordinal_mappings:
  - values: ['Av', 'Gd', 'Mn', 'No', 'NA']
    mapping: {Av: 5, Gd: 4, Mn: 3, 'No': 2, NA: 1}
  - values: ['Ex', 'Fa', 'Gd', 'TA', 'NA']
    mapping: {Ex: 5, Fa: 4, Gd: 3, TA: 2, NA: 1}
  - values: ['Ex', 'Fa', 'Gd', 'TA']
    mapping: {Ex: 4, Fa: 3, Gd: 2, TA: 1}
  - values: ['GdPrv', 'GdWo', 'MnPrv', 'MnWw', 'NA']
    mapping: {GdPrv: 5, GdWo: 4, MnPrv: 3, MnWw: 2, NA: 1}
  - values: ['Ex', 'Fa', 'Gd', 'Po', 'TA']
    mapping: {Ex: 5, Fa: 4, Gd: 3, Po: 2, TA: 1}
  - values: ['Ex', 'Fa', 'Gd', 'Po', 'TA', 'NA']
    mapping: {Ex: 6, Fa: 5, Gd: 4, Po: 3, TA: 2, NA: 1}
  - values: ['Mix', 'FuseP', 'FuseF', 'FuseA', 'SBrkr']
    mapping: {Mix: 1, FuseP: 2, FuseF: 3, FuseA: 4, SBrkr: 5}
  - values: ['Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ']
    mapping: {Sal: 1, Sev: 2, Maj2: 3, Maj1: 4, Mod: 5, Min2: 6, Min1: 7, Typ: 8}
  - values: ['N', 'P', 'Y']
    mapping: {N: 1, P: 2, Y: 3}
  - values: ['AllPub', 'NoSeWa', 'NoSewr']
    mapping: {AllPub: 3, NoSeWa: 2, NoSewr: 1}
  - values: ['GLQ', 'ALQ', 'BLQ', 'Rec', 'LwQ', 'Unf', 'NA']
    mapping: {GLQ: 6, ALQ: 5, BLQ: 4, Rec: 3, LwQ: 2, Unf: 1, NA: 1}
  - values: ['Gtl', 'Mod', 'Sev']
    mapping: {Gtl: 3, Mod: 2, Sev: 1}
  - values: ['IR3', 'IR2', 'IR1', 'Reg']
    mapping: {IR3: 1, IR2: 2, IR1: 3, Reg: 4}
  - values: ['Fin', 'RFn', 'Unf', 'NA']
    mapping: {Fin: 4, RFn: 3, Unf: 2, NA: 1}
