name: iowa_dream
channels:
  - defaults
  - conda-forge
dependencies:
 # defaults
  - python>=3.8
  - pip
  - pre-commit
  - pytest>=6
  - pytest-cov
  - setuptools-scm
  # data
  - pandas
  - polars
  - numpy
  - dask-ml
  - optuna
  - optuna-integration[lightgbm]
  - pydantic
  - yaml
  # interactive
  - ipykernel
  - jupyterlab
  # plots
  - matplotlib
  - seaborn
  # ml
  - glum
  - lightgbm
  - scikit-learn
  - shap
  - dalex
  # additional dependencies from file context
  - pathlib
  - kaggle
  - typing
  - scipy
  - lightgbm
  - statsmodels
